### PR TITLE
RHMAP-10130 Update to Swift 3

### PR DESCRIPTION
**Pull request by aidenkeating**

### CODE REVIEW

**Comment by aidenkeating** [comment]
@jcesarmobile Would you mind taking a look please? 😄

**Comment by jcesarmobile** [comment]
Change the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` to `$(inherited)` to avoid the CocoaPods warnings.

**Comment by jcesarmobile** [comment]
LGTM, but we can't merge it until we fix FeedHenry problems and publish it to use the 5.0.0 version instead of my branch

**Comment by jcesarmobile** [comment]
just noticed that the README.md says fh-ios-swift-sdk : 4.2+, should be fh-ios-swift-sdk : 5+

**Comment by aidenkeating** [comment]
@corinnekrych Would you mind taking a look?

**Comment by corinnekrych** [comment]
👀

**Comment by corinnekrych** [comment]
@aidenkeating https://github.com/aidenkeating/welcome-ios-swift/pull/1
Minor changes: let me know if you agree
+1 to merge otherwise

**Pull request merged**
